import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Catapult",
  description: "Generated by Nishant Mishra",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className='min-h-screen w-full'>
          <main className='flex grow'>{children}</main>
        </div>

      </body>
    </html>
  );
}
